Instalamos dependencias

In [1]:
!pip install wget

Requirement already satisfied: wget in ./.venv/lib/python3.13/site-packages (3.2)

In [2]:
pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from wget import download
from os import path, listdir

Descargamos la base

In [4]:
if not path.exists("schema.csv"):
  download("https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/schema.csv")
if not path.exists("results.csv"):
  download("https://media.githubusercontent.com/media/StackExchange/Survey/6ae2209cd35a55e92739ba82f7887fb86807a069/packages/archive/2025/results.csv")

Abrimos los archivos

In [5]:
raw_dataset = pd.read_csv("results.csv")
schema_dataset = pd.read_csv("schema.csv")

schema_dataset

/tmp/ipykernel_4601/3186393885.py:1: DtypeWarning: Columns (56: JobSatPoints_15_TEXT, 74: DatabaseHaveEntry, 92: DevEnvHaveEntry, 97: SOTagsHaveEntry, 98: SOTagsWant Entry, 105: OfficeStackWantEntry, 109: CommPlatformHaveEntr, 110: CommPlatformWantEntr, 132: SO_Actions_15_TEXT, 162: AIAgentOrchestration, 165: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_dataset = pd.read_csv("results.csv")

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

Leemos las columnnas

In [6]:
raw_dataset.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=172)

Leemos el dataset

In [22]:
raw_dataset.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [21]:
raw_dataset.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,...,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,...,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,...,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,...,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,...,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,...,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,...,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

Imprimimos el resumen estadistico

In [8]:
raw_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

Vemos solamente las de tipo float

In [9]:
raw_dataset.select_dtypes(include="float").columns

Index(['WorkExp', 'YearsCode', 'TechEndorse_1', 'TechEndorse_2',
       'TechEndorse_3', 'TechEndorse_4', 'TechEndorse_5', 'TechEndorse_6',
       'TechEndorse_7', 'TechEndorse_8', 'TechEndorse_9', 'TechEndorse_13',
       'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5',
       'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13',
       'TechOppose_16', 'TechOppose_15', 'JobSatPoints_1', 'JobSatPoints_2',
       'JobSatPoints_3', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6',
       'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10',
       'JobSatPoints_11', 'JobSatPoints_13', 'JobSatPoints_14',
       'JobSatPoints_15', 'JobSatPoints_16', 'ToolCountWork',
       'ToolCountPersonal', 'CompTotal', 'SO_Actions_1', 'SO_Actions_16',
       'SO_Actions_3', 'SO_Actions_4', 'SO_Actions_5', 'SO_Actions_6',
       'SO_Actions_9', 'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15',
       'ConvertedCompYearly', 'JobSat'],
      dtype='str')

Vemos solamente las de tipo string

In [10]:
raw_dataset.select_dtypes(include="string").columns

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow', 'DevType',
       ...
       'AIAgentKnowledge', 'AIAgentKnowWrite', 'AIAgentOrchestration',
       'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite',
       'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman', 'AIOpen'],
      dtype='str', length=119)

Vemos las filas columnas que no estan representadas en schema.csv

In [11]:
float_cols_dataset = set(raw_dataset.select_dtypes(include="float").columns)
string_cols_dataset = set(raw_dataset.select_dtypes(include="string").columns)

cols_dataset = set(raw_dataset.columns)
cols_schema  = set(schema_dataset["qname"])

float_faltan_en_schema =  float_cols_dataset - cols_schema
string_faltan_en_schema = string_cols_dataset - cols_schema

print(f"Faltan en el esquema: {len(float_faltan_en_schema)} columnas float")
for falta in sorted(float_faltan_en_schema):
    print(falta)
print("-" * 90)

print(f"Faltan en el esquema: {len(string_faltan_en_schema)} columnas string")
for falta in sorted(string_faltan_en_schema):
    print(falta)
print("-" * 90)

faltan_en_schema = cols_dataset - cols_schema
print(f"Faltan en el esquema: {len(faltan_en_schema)} columnas")
for falta in sorted(faltan_en_schema):
    print(falta)
print("-" * 90)
no_existen_en_dataset = cols_schema - cols_dataset
print(f"No existen en el dataset: {len(no_existen_en_dataset)}")
for no_existe in sorted(no_existen_en_dataset):
    print(no_existe)

Faltan en el esquema: 1 columnas float
ConvertedCompYearly
------------------------------------------------------------------------------------------
Faltan en el esquema: 44 columnas string
AIAgentChallengesNeutral
AIAgentChallengesSomewhat agree
AIAgentChallengesSomewhat disagree
AIAgentChallengesStrongly agree
AIAgentChallengesStrongly disagree
AIAgentImpactNeutral
AIAgentImpactSomewhat agree
AIAgentImpactSomewhat disagree
AIAgentImpactStrongly agree
AIAgentImpactStrongly disagree
AIModelsAdmired
AIModelsHaveWorkedWith
AIModelsWantToWorkWith
AIToolCurrently mostly AI
AIToolCurrently partially AI
AIToolDon't plan to use AI for this task
AIToolPlan to mostly use AI
AIToolPlan to partially use AI
CommPlatformAdmired
CommPlatformHaveWorkedWith
CommPlatformWantToWorkWith
DatabaseAdmired
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DevEnvsAdmired
DevEnvsHaveWorkedWith
DevEnvsWantToWorkWith
LanguageAdmired
LanguageHaveWorkedWith
LanguageWantToWorkWith
OfficeStackAsyncAdmired
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
OpSysPersonal use
OpSysProfessional use
PlatformAdmired
PlatformHaveWorkedWith
PlatformWantToWorkWith
SOTagsAdmired
SOTagsHaveWorkedWith
SOTagsWantToWorkWith
WebframeAdmired
WebframeHaveWorkedWith
WebframeWantToWorkWith
------------------------------------------------------------------------------------------
Faltan en el esquema: 46 columnas
AIAgentChallengesNeutral
AIAgentChallengesSomewhat agree
AIAgentChallengesSomewhat disagree
AIAgentChallengesStrongly agree
AIAgentChallengesStrongly disagree
AIAgentImpactNeutral
AIAgentImpactSomewhat agree
AIAgentImpactSomewhat disagree
AIAgentImpactStrongly agree
AIAgentImpactStrongly disagree
AIModelsAdmired
AIModelsHaveWorkedWith
AIModelsWantToWorkWith
AIToolCurrently mostly AI
AIToolCurrently partially AI
AIToolDon't plan to use AI for this task
AIToolPlan to mostly use AI
AIToolPlan to partially use AI
CommPlatformAdmired
CommPlatformHaveWorkedWith
CommPlatformWantToWorkWith
ConvertedCompYearly
DatabaseAdmired
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DevEnvsAdmired
DevEnvsHaveWorkedWith
DevEnvsWantToWorkWith
LanguageAdmired
LanguageHaveWorkedWith
LanguageWantToWorkWith
OfficeStackAsyncAdmired
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
OpSysPersonal use
OpSysProfessional use
PlatformAdmired
PlatformHaveWorkedWith
PlatformWantToWorkWith
ResponseId
SOTagsAdmired
SOTagsHaveWorkedWith
SOTagsWantToWorkWith
WebframeAdmired
WebframeHaveWorkedWith
WebframeWantToWorkWith
------------------------------------------------------------------------------------------
No existen en el dataset: 13
AIAgentChallenges
AIAgentImpact
AIModels
AITool
CommPlatform
Database
DevEnvs
Language
OfficeStackAsync
OpSys
Platform
SOTags
Webframe

In [12]:
print(schema_dataset[schema_dataset["qname"]=="Language"])
print(schema_dataset.loc[schema_dataset["qid"] == "QID34", "question"].values)

      qid     qname                                           question  \
76  QID34  Language  Which <b>programming, scripting, and markup la...

      type  sub  sq_id
76  Matrix  NaN    NaN
<StringArray>
['Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)']
Length: 1, dtype: str

In [13]:
[col for col in raw_dataset.columns if "language" in col.lower()]

['LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry']

Busco las preguntas del schema sin repetir

In [18]:
schema_dataset.drop_duplicates(subset="question", keep="first")[["qname", "question"]].values.tolist()

[['TechEndorse_1',
  'What attracts you to a technology or causes you to endorse it (most to least important)?'],
 ['TechOppose_1',
  'What would turn you off or cause you to reject it (most to least important)?'],
 ['JobSatPoints_1',
  'Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):'],
 ['SO_Actions_1',
  'When visiting Stack Overflow, which following activities are you most interested in?  Please rank the following so the first activity is what most interests you and last is your least interested activity.'],
 ['MainBranch',
  'Are you someone who writes code? Please select one of the following options that best describes you today.'],
 ['Age', 'What is your age?'],
 ['EdLevel',
  'Which of the following best describes the highest level of formal education that you’ve completed? '],
 ['Employment',
  'Which of the following best describes your current employment status?<br>'],
 ['EmploymentAddl',
  'Which of the following <strong>additional</strong> activities are you currently engaged in?'],
 ['WorkExp',
  "How many years of professional work experience do you have? Please round to the nearest whole number, excluding any decimal points.  If your answer is '0', please leave blank."],
 ['LearnCodeChoose',
  'Did you begin learning to code or learn a new coding skill/programming language in the last year?'],
 ['LearnCode',
  'How did you learn to code in the past year? Select all that apply.'],
 ['LearnCodeAI',
  'Did you spend time in the last year learning AI programming or AI-enabled tooling on your own or at work?'],
 ['AILearnHow',
  'How did you learn to code for AI in the past year? Select all that apply.'],
 ['YearsCode',
  'Including any education, how many years have you been coding in total?  Please round to the nearest whole number, excluding any decimal points.'],
 ['DevType',
  'Which of the following describes your current job or the job you had for the most time in the past year?'],
 ['OrgSize',
  'Approximately how many people are employed by your employer?  This should only include your primary company, and if there was more than one employer please consider the one you spent most of your time working for in the past year.'],
 ['ICorPM', 'Are you an individual contributor or people manager?'],
 ['RemoteWork', 'Which best describes your current work situation?'],
 ['PurchaseInfluence',
  'Have you <strong>influenced or endorsed</strong> a new technology purchase at your organization or sole proprietor job in the past year?'],
 ['TechEndorseIntro',
  'When you&rsquo;re in a position to <strong>influence or endorse a technology</strong>, whether at work, for school, or for a personal project you&rsquo;re responsible for, what features or attributes matter most when deciding to support a tool? What factors would be deal-breakers?<br />\n<br />\nFirst, select the context (work, school, personal project).  Then, rank the following features in order of importance.\u200b\u200b\u200b\u200b\u200b\u200b'],
 ['Industry', 'What industry do you work for in?'],
 ['JobSat',
  'How satisfied are you in your current professional developer role?'],
 ['AIThreat', 'Do you believe AI is a threat to your current job?'],
 ['NewRole',
  'Have you considered a career change or transitioned into a new role in the past year?'],
 ['ToolCountWork',
  'For your <b>primary work role</b> (student, developer, or technologist) over the past year:\n<br><br>Excluding general operating systems (like Windows or macOS) and web browsers, <b>how many distinct software applications or platforms</b> did you regularly use to create, analyze, manage, or share information in order to do your job?\n\nPlease enter a whole number below with no punctuation, or leave blank.'],
 ['ToolCountPersonal',
  '<b></b>For your <b>side projects or other personal work</b> over the past year (focus on the project you spent the most time on if applicable):\n<br><br>Excluding general operating systems and web browsers, how many <b>distinct software applications or platforms</b> did you regularly use to do your job? Please enter a whole number below with no punctuation, or leave blank.'],
 ['Country', 'Where do you live?'],
 ['Currency',
  "Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."],
 ['CompTotal',
  'What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions) in terms of your day-to-day currency?  Please enter a whole number in the box below, without any punctuation.  If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty. '],
 ['LanguageChoice',
  'Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come?  Here, we are referring to anything you use that is conventionally referred to as code.'],
 ['Language',
  'Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)'],
 ['LanguagesHaveEntry',
  'Was the programming language you use not listed above?  List below, separated by a comma and a space for each, the programming language(s) <strong>you used in the past year</strong>.'],
 ['LanguagesWantEntry',
  'Was the programming language you want to use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you want to use next year</strong>.'],
 ['DatabaseChoice',
  'Did you work with database environments in the last year or do you plan to in the year to come?  Here, we are referring to a system of managing structured data, mostly outside of your local machine.'],
 ['Database',
  'Which <b>database environments </b>have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)'],
 ['DatabaseHaveEntry',
  'Was the database environment you use not listed above?  List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.'],
 ['DatabaseWantEntry',
  'Was the database environment you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.'],
 ['PlatformChoice',
  'Did you work with cloud platforms, containerization/orchestration tools, package managers, build tools or infrastructure as code solutions in the last year or do you plan to in the year to come?  Here, we are referring to tooling that automates, manages, and scales the entire application lifecycle, often leveraging remote, virtualized resources.'],
 ['Platform',
  'Which <b>cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the platform and want to continue to do so, please check both boxes in that row.)'],
 ['PlatformHaveEntry',
  'Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you use not listed above?  List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.'],
 ['PlatformWantEntry',
  'Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you want to use not listed above?  List below, separated by a comma and a space for each, what<strong>you want to use next year</strong>.'],
 ['WebframeChoice',
  'Did you work with web frameworks and web technologies in the last year or do you plan to in the year to come?  Here, we are referring to technology that helps website and web apps materialize.'],
 ['Webframe',
  'Which <b>web frameworks and web technologies</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)'],
 ['WebframeHaveEntry',
  'Were the web frameworks and web technologies you use not listed above?  List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.'],
 ['WebframeWantEntry',
  'Were the web frameworks and web technologies you want to use not listed above?  List below, separated by a comma and a space for each, the what <strong>you want to use next year</strong>.'],
 ['DevEnvsChoice',
  'Did you work with development environments or AI-enabled code editing tools in the last year or do you plan to in the year to come?  Here, we are referring to programs like VS Code that allow you to write, edit and save code easily and help you share code with other developers or AI agents.'],
 ['DevEnvs',
  'Which <strong>development environments and AI-enabled code editing tools</strong> did you use regularly over the past year, and which do you want to work with over the next year? Please check all that apply.'],
 ['DevEnvHaveEntry',
  'Was the developer environment or AI-enabled code editing tool you use not listed above?  List below, separated by a comma and a space for each, what<strong> you used in the past year</strong>.'],
 ['DevEnvWantEntry',
  'Was the developer environment or AI-enabled code editing tool you want to use not listed above?  List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.'],
 ['SOTags',
  'Which rising technology of the added as <b>new tag or tag subject area on Stack Overflow</b> in the last three years <strong>have you used</strong> regularly in the past year, and which do you <strong>want to work with</strong> over the next year? Please check all that apply.<br>\n '],
 ['SOTagsHaveEntry',
  'Was the new tag on Stack Overflow (i.e. added in the last 2 - 3 years) you use not listed above?  List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.'],
 ['SOTagsWant Entry',
  'Was the new tag on Stack Overflow (i.e. added in the last 2 - 3 years) you want to use not listed above?  List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.'],
 ['OpSys', 'What is the primary <b>operating system</b> in which you work? '],
 ['OfficeStackAsync',
  'Which <b>collaborative work management and/or code documentation tools</b> did you use regularly over the past year, and which do you want to work with over the next year? Select all that apply'],
 ['OfficeStackHaveEntry',
  'Was the collaborative work management and/or code documentation tools you use not listed above?  List below, separated by a comma and a space for each, what you used in the past year.'],
 ['OfficeStackWantEntry',
  'Was the collaborative work management and/or code documentation tools you want to use not listed above?  List below, separated by a comma and a space for each, what you used in the past year.'],
 ['CommPlatform',
  'Which <b>community platforms</b> have you utilized considerably or consistently in the past year, and which would you like to use next year?  Select all that apply.'],
 ['CommPlatformHaveEntr',
  'Was the community platform you use not listed above?  List below, separated by a comma and a space for each, what you used in the past year.'],
 ['CommPlatformWantEntr',
  'Was the community platform you want to use not listed above?  List below, separated by a comma and a space for each, what you used in the past year.'],
 ['AIModelsChoice',
  'Did you utilize or integrate specific Large Language Models (LLMs) to power your development tools or applications in the last year?  Here, we are referring to models like GPT-4, Llama, Claude, etc., within your development environments or solutions.'],
 ['AIModels',
  'Which <b>LLM models for AI tools</b> have you used for development work in the past year, and which would you like to use next year?  Select all that apply.'],
 ['AIModelsHaveEntry',
  'Was the LLM model for AI tools you use not listed above?  List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.'],
 ['AIModelsWantEntry',
  'Was the LLM model for AI tools you want to use not listed above?  List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.'],
 ['SOAccount', 'Do you have a Stack Overflow account?'],
 ['SOVisitFreq', 'How frequently would you say you visit Stack Overflow?'],
 ['SODuration', 'How long have you used Stack Overflow?'],
 ['SOPartFreq',
  'How frequently would you say you participate in Q&amp;A on Stack Overflow? By participate we mean ask, answer, and vote or comment on questions.'],
 ['SO_Dev_Content',
  'Whether it be to solve a problem, for career growth or connecting with a community of developers, is there an alternative to the Q&amp;A format you prefer using today or would like to see on Stack Overflow to get what you need? Select all that apply.'],
 ['SOComm',
  'Do you consider yourself a member of the Stack Overflow community?'],
 ['SOFriction',
  'When you visit Stack Overflow, how often is it a result of encountering issues from AI or AI-enabled tools that require extra time or effort to fix, understand, or debug?'],
 ['AISelect', 'Do you currently use AI tools in your development process?'],
 ['AISent',
  'How favorable is your stance on using AI tools as part of your development workflow?'],
 ['AIAcc',
  'How much do you trust the accuracy of the output from AI tools as part of your development workflow?'],
 ['AIComplex',
  'How well do the AI tools you use in your development workflow handle complex tasks?'],
 ['AITool',
  'Which parts of your development workflow are you currently integrating into AI or using AI tools to accomplish or plan to use AI to accomplish over the next 3 - 5 years?  Please select one for each scenario.'],
 ['AIFrustration',
  'When using AI tools, which of the following problems or frustrations have you encountered? Select all that apply.'],
 ['AIExplain',
  'In your own words, is &quot;vibe coding&quot; part of your professional development work? For this question, we define vibe coding according to the <a href="https://en.wikipedia.org/wiki/Vibe_coding" target="_blank">Wikipedia definition</a>, the process of generating software from LLM prompts.'],
 ['AIAgents',
  'Are you using AI agents in your work (development or otherwise)?  AI agents refer to autonomous software entities that can operate with minimal to no direct human intervention using artificial intelligence techniques.'],
 ['AIAgentChange',
  'Have AI tools or AI agents changed how you complete development work in the past year?'],
 ['AIAgent_Uses',
  'What industry purposes or specific tasks are you using AI agents in your development work? Select all that apply from both lists.'],
 ['AgentUsesGeneral', ' '],
 ['AIAgentImpact',
  'To what extent do you agree with the following statements regarding the impact of AI agents on your work as a developer?'],
 ['AIAgentChallenges',
  'To what extent do you agree with the following statements regarding AI agents?'],
 ['AIAgentKnowledge',
  'You indicated you use or develop AI agents as part of your development work.  Have you used any of the following tools for AI agent memory or data management in the past year?'],
 ['AIAgentKnowWrite',
  'Was the tool or tools for AI agent orchestration or agent frameworks you used in the past year not listed above?  Please write them below separated by a comma and space if there are more than one.'],
 ['AIAgentOrchestration',
  'You indicated you use or develop AI agents as part of your development work.  Have you used any of the following tools for AI agent orchestration or agent frameworks in the past year?'],
 ['AIAgentObserveSecure',
  'You indicated you use or develop AI agents as part of your development work.  Have you used any of the following tools for AI agent observability, monitoring or security in the past year?'],
 ['AIAgentObsWrite',
  'Was the tool or tools for AI agent observability, monitoring or security you used in the past year not listed above?  Please write them below separated by a comma and space if there are more than one.'],
 ['AIAgentExternal',
  'You indicated you use or develop AI agents as part of your development work.  Have you used any of the following out-of-the-box agents, copilots or assistants?'],
 ['AIAgentExtWrite',
  'Was the out-of-the-box agents, copilots or assistants you used in the past year not listed above?  Please write them below separated by a comma and space if there are more than one.'],
 ['AIHuman',
  'In the future, if AI can do most coding tasks, in which situations would you still want to ask another person for help? Select all that apply.'],
 ['AIOpen',
  'Looking ahead 3–5 years, what skills do you believe will remain valuable for developers even as AI tools become more capable? Please describe.']]